const ENDPOINT = process.env.NEXT_PUBLIC_ENDPOINT;
const BE_URL = process.env.NEXT_PUBLIC_BE_URL;
const SEARCH_ENGINE_ID = process.env.NEXT_PUBLIC_SEARCH_ENGINE_ID;
const ENV = process.env.NEXT_PUBLIC_ENV;

export { ENDPOINT, BE_URL, SEARCH_ENGINE_ID, ENV };
